image: fpco/stack-build:latest

# https://docs.gitlab.com/ee/ci/yaml/#stages
# jobs of the same stage are executed in parallel
stages:
  - build
  - test

# https://docs.gitlab.com/ee/ci/variables/#using-the-ci-variables-in-your-job-scripts
variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

# https://docs.gitlab.com/ee/ci/yaml/#cache
cache:
  paths:
    - .stack-work/
    - .stack-root/

build-lts-16:
  stage: build
  script:
    - stack --no-terminal --resolver=lts-16 build --fast

build-lts-17:
  stage: build
  script:
    - stack --no-terminal --resolver=lts-17 build --fast

build-lts-18:
  stage: build
  script:
    - stack --no-terminal --resolver=lts-18 build --fast

build-lts-19:
  stage: build
  script:
    - stack --no-terminal --resolver=lts-19 build --fast

test-lts-16:
  stage: test
  script:
    - stack --no-terminal  --resolver=lts-16 test --fast

test-lts-17:
  stage: test
  script:
    - stack --no-terminal  --resolver=lts-17 test --fast

test-lts-18:
  stage: test
  script:
    - stack --no-terminal  --resolver=lts-18 test --fast

test-lts-19:
  stage: test
  script:
    - stack --no-terminal  --resolver=lts-19 test --fast
