resolver: lts-24.16

packages:
- .
- examples

extra-deps:
- crypton-connection-0.4.1

# old weeder implementation
# ghc-options: {"$locals": -ddump-to-file -ddump-hi}

# for stan and weeder 2.0
# ghc-options:
#  "$locals": -fwrite-ide-info -hiedir=.hie